### ISSUE TITLE
IV Frame 1 gives results of IV frame 0 in game

### ISSUE THREAD

**Issue by AES256orSomething** [Bambo-Rambo/RNGReporter#3]
I was following all the guides that said to set IV frame to 1 and was trying to hit a specific Shiny and IV frame for starter in in Black 2 on a cartridge and finally got the shiny frame but noiticed the stats were wrong and checked the IVs and found they were actually the IVs for IV frame 0 and not 1

I then downloaded the Admiral Fish fork to see if there was a difference and the IV frame was offset by one in your fork.
So IV frame 1 in your fork was IV frmae 2 in Admiral fish fork (and also IV frame 2 in game)

I atttached screenshot of the tool showing results and of the IVs of the pokemon from in game

![RNGReporter_C3p6OexFv5](https://github.com/Bambo-Rambo/RNGReporter/assets/25196493/18699c7a-bd8a-4704-b459-d9c10265f8e3)
![Honeyview_EOJ6Q0O5qR](https://github.com/Bambo-Rambo/RNGReporter/assets/25196493/5626c7c8-62bf-4212-a41f-e83c2672dcc7)

**Comment by Bambo-Rambo** [comment]
Frames actually start from 0 not 1. This is for both the PID and IV frames.
I made this change so users always have to land on their target frame which is easy to remember, rather than aiming for -1, -2 etc depending on the encounter type.

**Comment by AES256orSomething** [comment]
Oh, sorry I wasnt aware and that makes sense!

Then it may be a good idea then to make a note of the change in the readme? Since all past guides on RNG reporter say to set it to 1 and there may be people like me following them and woulnd't know to change it to 0 to get the same results as the guides.

**Comment by Bambo-Rambo** [comment]
All changes need to be mentioned in the readme file at some point. Though most people who use this fork are generally aware.
